 version: '2'
 services:
   db:
     image: postgres:9.6
     environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=voty
      - POSTGRES_PASSWORD=204rkmafd90-ad
     volumes:
       - ./data/db:/var/lib/postgresql/data
   web:
     build: .
     environment:
      - DATABASE_URL=postgres://voty:204rkmafd90-ad@db/voty
      - VIRTUAL_HOST=abstimmen.bewegung.jetzt
      - LETSENCRYPT_DOMAIN=abstimmen.bewegung.jetzt
      - LETSENCRYPT_EMAIL=benjamin.kampmann@bewegung.jetzt
     env_file: secrects.env
     command: gunicorn -w 3 -b 0.0.0.0 voty.wsgi
     volumes:
       - ./data/public:/code/public
     expose:
       - 8000
     links:
       - db
 networks:
  default:
    external:
      name: nginx-proxy
